<#
.SYNOPSIS
    Installs/Updates AVM into $PROFILE.
    Auto-elevates, sets permissions, and guides the user on restart.
#>

# --- 1. AUTO-ELEVATE TO ADMINISTRATOR ---
$currentPrincipal = New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent())
if (-not $currentPrincipal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    Write-Host "[INFO] Requesting Administrator privileges..." -ForegroundColor Yellow
    $processInfo = New-Object System.Diagnostics.ProcessStartInfo
    $processInfo.FileName = "powershell.exe"
    $processInfo.Arguments = "-NoProfile -ExecutionPolicy Bypass -File `"$PSCommandPath`""
    $processInfo.Verb = "runas"
    try {
        [System.Diagnostics.Process]::Start($processInfo)
    } catch {
        Write-Error "Failed to restart as Admin. Please run manually."
    }
    exit
}

# --- 2. DEFINE THE AVM SCRIPT CONTENT ---
$AvmScriptContent = @'

#region AVM_MANAGER
# =============================================================================
#  ANGULAR VERSION MANAGER (AVM)
#  Auto-generated by install_avm.ps1
#  Map Source: https://angular.dev/reference/versions (As of Jan 2026)
# =============================================================================
function avm {
    param (
        [Parameter(Mandatory=$true)]
        [string]$Version
    )

    # --- CONFIGURATION: Highest Supported Node LTS per Angular Version ---
    $FallbackNodeVer = "22" 

    $NodeMap = @{
        # Future / Latest (2026)
        "21" = "24"
        "20" = "22"
        "19" = "22"

        # Modern (Ivy / Standalone Era)
        "18" = "20"
        "17" = "20"
        "16" = "18"
        "15" = "18"
        "14" = "16"

        # Legacy (ViewEngine Era)
        "13" = "16"; "12" = "14"; "11" = "12"
        "10" = "12"; "9"  = "12"
        
        # Ancient
        "8"  = "10"; "7"  = "10"; "6"  = "8"
        "5"  = "8";  "4"  = "6"
    }

    # --- LOGIC ---
    if ($Version -match "\.") {
        $AngularMajor = $Version.Split('.')[0]
        $IsSpecific = $true
    } else {
        $AngularMajor = $Version
        $IsSpecific = $false
    }

    $TargetNodeMajor = $NodeMap[$AngularMajor]

    if ($null -eq $TargetNodeMajor) {
        Write-Host "[WARN] Unknown Angular version: $AngularMajor" -ForegroundColor Yellow
        Write-Host "   Using fallback Node v$FallbackNodeVer. Proceed? (Y/N)"
        if ((Read-Host) -notmatch "^[Yy]$") { return }
        $TargetNodeMajor = $FallbackNodeVer
    }

    Write-Host "[INFO] Request: Angular $Version requires Node v$TargetNodeMajor.x" -ForegroundColor Cyan

    # 1. Smart NVM Switch
    $nvmList = nvm list
    $pattern = "\b$TargetNodeMajor\.\d+\.\d+\b"

    if ($nvmList -match $pattern) {
        $BestLocalNode = $Matches[0]
        $CurrentNode = node -v 2>$null
        if ($CurrentNode -ne "v$BestLocalNode") {
            Write-Host "[ACTION] Switching to Node $BestLocalNode..."
            nvm use $BestLocalNode
        }
    } else {
        Write-Host "[INFO] Node v$TargetNodeMajor.x not found locally. Installing..." -ForegroundColor Yellow
        nvm install $TargetNodeMajor
        nvm use $TargetNodeMajor
    }

    if ($LASTEXITCODE -ne 0) { Write-Error "Failed to switch Node."; return }

    # 2. Angular CLI Check
    $npmOutput = npm list -g @angular/cli --depth=0 --json 2>$null | ConvertFrom-Json 
    $InstalledFull = if ($npmOutput.dependencies.'@angular/cli') { $npmOutput.dependencies.'@angular/cli'.version } else { $null }
    $NeedsInstall = $false

    if (-not $InstalledFull) {
        Write-Host "[WARN] Angular CLI not found." -ForegroundColor Yellow; $NeedsInstall = $true
    } else {
        if ($IsSpecific -and $InstalledFull -ne $Version) { $NeedsInstall = $true }
        elseif (-not $IsSpecific -and $InstalledFull.Split('.')[0] -ne $AngularMajor) { $NeedsInstall = $true }
    }

    if ($NeedsInstall) {
        if ($InstalledFull) { Write-Host "[INFO] Uninstalling old v$InstalledFull..." -ForegroundColor Gray; npm uninstall -g @angular/cli }
        Write-Host "[ACTION] Installing Angular CLI @ $Version..." -ForegroundColor Cyan
        npm install -g @angular/cli@$Version
        Write-Host "[SUCCESS] Installed Angular CLI $Version" -ForegroundColor Green
    } else {
        Write-Host "[SUCCESS] Ready! Using Node $(node -v) and Angular CLI v$InstalledFull" -ForegroundColor Green
    }
}
#endregion AVM_MANAGER

'@

# --- 3. MANAGE PROFILE ---
$ProfilePath = $PROFILE
Write-Host "[SETUP] Target Profile: $ProfilePath" -ForegroundColor Cyan

if (-not (Test-Path $ProfilePath)) {
    Write-Host "   [INFO] Profile not found. Creating..." -ForegroundColor Yellow
    New-Item -Path $ProfilePath -Type File -Force | Out-Null
}

$CurrentContent = Get-Content -Path $ProfilePath -Raw -ErrorAction SilentlyContinue
if ($null -eq $CurrentContent) { $CurrentContent = "" }

$RegionRegex = "(?ms)^\s*#region AVM_MANAGER.*?#endregion AVM_MANAGER\s*$"

if ($CurrentContent -match $RegionRegex) {
    Write-Host "[UPDATE] Updating existing AVM installation..." -ForegroundColor Yellow
    $NewContent = $CurrentContent -replace $RegionRegex, $AvmScriptContent
} else {
    Write-Host "[INSTALL] Installing AVM..." -ForegroundColor Green
    $NewContent = $CurrentContent + "`r`n`r`n" + $AvmScriptContent
}

Set-Content -Path $ProfilePath -Value $NewContent -Encoding UTF8

# --- 4. EXECUTION POLICY ---
Write-Host "[SETUP] Enabling scripts..." -ForegroundColor Cyan
try {
    Set-ExecutionPolicy RemoteSigned -Scope CurrentUser -Force
    Write-Host "   [SUCCESS] Policy set." -ForegroundColor Green
} catch {
    Write-Host "   [ERROR] Could not set policy." -ForegroundColor Red
}

# --- 5. FINISH & AUTO-RELOAD ---
Write-Host "`n============================================" -ForegroundColor Green
Write-Host " AVM INSTALLED SUCCESSFULLY " -ForegroundColor Green
Write-Host "============================================" -ForegroundColor Green

try {
    # Attempt to reload profile immediately in this session
    . $PROFILE
    if (Get-Command "avm" -ErrorAction SilentlyContinue) {
        Write-Host " [SUCCESS] AVM loaded! You can type 'avm 17' now." -ForegroundColor Cyan
    } else {
        throw "Not loaded"
    }
} catch {
    # If we are in a sub-process (Admin window), the reload won't affect the user's main window
    Write-Host "To start using AVM, you have two options:"
    Write-Host " 1. Run this command: . `$PROFILE" -ForegroundColor Yellow
    Write-Host "    OR"
    Write-Host " 2. Close the Powershell session and open a new Powershell session" -ForegroundColor Blue
}

Write-Host "`nPress Enter to exit..."
Read-Host
