# --- 1. AUTO-ELEVATE ---
$currentPrincipal = New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent())
if (-not $currentPrincipal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    Write-Host "[INFO] Requesting Admin to repair profile..." -ForegroundColor Yellow
    $processInfo = New-Object System.Diagnostics.ProcessStartInfo
    $processInfo.FileName = "powershell.exe"
    $processInfo.Arguments = "-NoProfile -ExecutionPolicy Bypass -File `"$PSCommandPath`""
    $processInfo.Verb = "runas"
    try { [System.Diagnostics.Process]::Start($processInfo) } catch { Write-Error "Failed to elevate."; exit }
    exit
}

# --- 2. DEFINE THE FIXED SCRIPT (Added .Trim() calls) ---
$AvmScriptContent = @'

#region AVM_MANAGER
# =============================================================================
#  ANGULAR VERSION MANAGER (AVM)
#  Auto-generated by install_avm.ps1
#  Fixed: Handles whitespace/newline trimming
# =============================================================================
function avm {
    param (
        [Parameter(Mandatory=$true)]
        [string]$Version
    )

    $FallbackNodeVer = "22"

    $NodeMap = @{
        "21" = "24"; "20" = "22"; "19" = "22"
        "18" = "20"; "17" = "20"; "16" = "18"; "15" = "18"; "14" = "16"
        "13" = "16"; "12" = "14"; "11" = "12"
        "10" = "12"; "9"  = "12"
        "8"  = "10"; "7"  = "10"; "6"  = "8"; "5"  = "8";  "4"  = "6"
    }

    # Clean the input version
    $Version = $Version.Trim()

    if ($Version -match "\.") {
        $AngularMajor = $Version.Split('.')[0]
        $IsSpecific = $true
    } else {
        $AngularMajor = $Version
        $IsSpecific = $false
    }

    $TargetNodeMajor = $NodeMap[$AngularMajor]

    # Handle Unknown Versions
    if ($null -eq $TargetNodeMajor) {
        Write-Host "[WARN] Unknown Angular version: $AngularMajor" -ForegroundColor Yellow
        Write-Host "   Using fallback Node v$FallbackNodeVer. Proceed? (Y/N)"
        if ((Read-Host) -notmatch "^[Yy]$") { return }
        $TargetNodeMajor = $FallbackNodeVer
    }

    # CRITICAL FIX: Trim whitespace/newlines from the target node version
    $TargetNodeMajor = "$TargetNodeMajor".Trim()

    Write-Host "[INFO] Request: Angular $Version requires Node v$TargetNodeMajor.x" -ForegroundColor Cyan

    # 1. Smart NVM Switch
    $nvmList = nvm list
    $pattern = "\b$TargetNodeMajor\.\d+\.\d+\b"

    if ($nvmList -match $pattern) {
        $BestLocalNode = $Matches[0].Trim()
        $CurrentNode = node -v 2>$null
        if ($CurrentNode -ne "v$BestLocalNode") {
            Write-Host "[ACTION] Switching to Node $BestLocalNode..."
            nvm use $BestLocalNode
        }
    } else {
        Write-Host "[INFO] Node v$TargetNodeMajor.x not found locally. Installing..." -ForegroundColor Yellow
        
        # Explicitly quote arguments to prevent NVM argument parsing errors
        nvm install "$TargetNodeMajor"
        nvm use "$TargetNodeMajor"
    }

    if ($LASTEXITCODE -ne 0) { Write-Error "Failed to switch Node."; return }

    # 2. Angular CLI Check
    $npmOutput = npm list -g @angular/cli --depth=0 --json 2>$null | ConvertFrom-Json 
    $InstalledFull = if ($npmOutput.dependencies.'@angular/cli') { $npmOutput.dependencies.'@angular/cli'.version } else { $null }
    $NeedsInstall = $false

    if (-not $InstalledFull) {
        Write-Host "[WARN] Angular CLI not found." -ForegroundColor Yellow; $NeedsInstall = $true
    } else {
        if ($IsSpecific -and $InstalledFull -ne $Version) { $NeedsInstall = $true }
        elseif (-not $IsSpecific -and $InstalledFull.Split('.')[0] -ne $AngularMajor) { $NeedsInstall = $true }
    }

    if ($NeedsInstall) {
        if ($InstalledFull) { Write-Host "[INFO] Uninstalling old v$InstalledFull..." -ForegroundColor Gray; npm uninstall -g @angular/cli }
        Write-Host "[ACTION] Installing Angular CLI @ $Version..." -ForegroundColor Cyan
        npm install -g @angular/cli@$Version
        Write-Host "[SUCCESS] Installed Angular CLI $Version" -ForegroundColor Green
    } else {
        Write-Host "[SUCCESS] Ready! Using Node $(node -v) and Angular CLI v$InstalledFull" -ForegroundColor Green
    }
}
#endregion AVM_MANAGER

'@

# --- 3. OVERWRITE PROFILE ---
$ProfilePath = $PROFILE
Write-Host "[REPAIR] Fixing Profile: $ProfilePath" -ForegroundColor Cyan

if (-not (Test-Path $ProfilePath)) { New-Item -Path $ProfilePath -Type File -Force | Out-Null }

$CurrentContent = Get-Content -Path $ProfilePath -Raw -ErrorAction SilentlyContinue
if ($null -eq $CurrentContent) { $CurrentContent = "" }

$RegionRegex = "(?ms)^\s*#region AVM_MANAGER.*?#endregion AVM_MANAGER\s*$"

if ($CurrentContent -match $RegionRegex) {
    Write-Host "[UPDATE] Overwriting corrupted AVM code..." -ForegroundColor Yellow
    $NewContent = $CurrentContent -replace $RegionRegex, $AvmScriptContent
} else {
    Write-Host "[INSTALL] Installing AVM..." -ForegroundColor Green
    $NewContent = $CurrentContent + "`r`n`r`n" + $AvmScriptContent
}

Set-Content -Path $ProfilePath -Value $NewContent -Encoding UTF8

Write-Host "[SUCCESS] Repair Complete." -ForegroundColor Green
Write-Host "Please close this window and open a NEW PowerShell window."
Write-Host "Press Enter to exit..."
Read-Host
